# Quantum Kernel Evaluation Pipeline

This notebook constructs the meta-dataset for the encoding circuit recommendation framework. It executes three stages:
1. Load 200 binary classification datasets (174 synthetic + 26 real-world)
2. Evaluate 9 encoding circuits × 3 classifiers (SVC, GPC, KRC) × 10 random splits per dataset
3. Compute 24 classical complexity metrics per dataset

Outputs: `taska_labels.csv`, `taskb_labels.csv`, `synthesis_df.csv` — inputs for the Majority Voting and LOOCV recommendation steps.

## 1. Setup

In [16]:
from Qsun.Qkernels import *
from Qsun.Qgates import *
from Qsun.Qmeas import *
from Qsun.Qcircuit import *
from Qsun.Qwave import *
from Qsun.Qencodes import *
from Qsun.Qdata import *

import numpy as np
import matplotlib.pyplot as plt
from datasets.load_data import *
from src.kernel_evaluation import *
from src.config import *

import problexity as px

np.random.seed(1234)

## 2. Kernel Evaluation Routines

`total_runs` evaluates all 9 encoding circuits × 3 classifiers on a single dataset, repeated over 10 random train/test splits. Each run applies PCA (if the dataset exceeds 4 features) and MinMax scaling to [0, π] before computing quantum kernel matrices via state fidelity.

`run_all_datasets` iterates `total_runs` across the full dataset collection.

In [17]:
def total_runs(dataset_name="Iris",
               raw_datasets=None,     
               encodings=None,
               n_layers=2,
               n_runs=10,
               test_size=0.2,
               random_state=42,
               feature_range=(0, np.pi),
               max_qubit=4):

    if encodings is None:
        encodings = get_available_encodings()

    print(f"Dataset: {dataset_name}")

    results_accumulator = {
        enc: {m: {"train": [], "test": []} for m in ["SVM", "GPC", "KRC"]}
        for enc in encodings
    }

    X_full, y_full = raw_datasets[dataset_name]

    for run in range(n_runs):
        seed = random_state + run

        X_train, X_test, y_train, y_test = train_test_split(
            X_full, y_full,
            test_size=test_size,
            random_state=seed,
            stratify=y_full
        )

        if X_train.shape[1] > max_qubit:
            pca = PCA(n_components=max_qubit, random_state=seed)
            X_train = pca.fit_transform(X_train)
            X_test = pca.transform(X_test)

        scaler = MinMaxScaler(feature_range=feature_range)
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        kernels = total_kernels(
            X_train, X_test,
            encoding_names=encodings,
            n_layers=n_layers,
            random_state=seed,
            verbose=False
        )

        for enc_name, (K_train, K_test) in kernels.items():
            for model_name in ["SVM", "GPC", "KRC"]:
                result = evaluate_kernel(
                    K_train, K_test, y_train, y_test,
                    enc_name, model_name
                )
                results_accumulator[enc_name][model_name]["train"].append(result.train_accuracy)
                results_accumulator[enc_name][model_name]["test"].append(result.test_accuracy)

        print(f"  Run {run+1}/{n_runs} completed", end='\r')

    print()

    all_results = {}
    for enc_name in encodings:
        enc_results = []
        for model_name in ["SVM", "GPC", "KRC"]:
            train_scores = results_accumulator[enc_name][model_name]["train"]
            test_scores = results_accumulator[enc_name][model_name]["test"]

            enc_results.append(KernelEvaluation(
                model_name=model_name,
                encoding_name=enc_name,
                train_accuracy=np.mean(train_scores),
                test_accuracy=np.mean(test_scores),
                train_std=np.std(train_scores),
                test_std=np.std(test_scores)
            ))
        all_results[enc_name] = enc_results

    return {"results": all_results}


def run_all_datasets(encodings=None, 
                     n_layers=2, 
                     n_runs=10, 
                     test_size=0.2, 
                     random_state=42, 
                     include_variants=True):

    datasets = load_extended_datasets(max_qubit=4, verbose=True)
   
    all_results = {}
    dataset_names = list(datasets.keys())
    
    print(f"Total datasets to process: {len(dataset_names)}")
    print("=" * 60)
    
    for idx, dataset_name in enumerate(dataset_names, 1):
        print(f"\n[{idx}/{len(dataset_names)}] Processing {dataset_name}...")
        
        result = total_runs(
            dataset_name=dataset_name,
            encodings=encodings,
            n_layers=n_layers,
            n_runs=n_runs,
            test_size=test_size,
            random_state=random_state,
            include_variants=include_variants
        )
        
        all_results[dataset_name] = result
    
    print("\n" + "=" * 60)
    print("All datasets processed!")
    
    return all_results

## 3. Summary Utilities

- `summary`: prints the encoding circuit × classifier accuracy table for a single dataset.
- `create_summary_table`: builds a cross-dataset DataFrame for one classifier, used for paper comparison tables.

In [18]:
def summary(all_results):
    print(f"{'Encoding':<22} {'Model':<6} {'Train':<18} {'Test':<18}")
    print("-" * 75)
    
    best_test_acc = 0
    best_config = None
    
    for encoding_name, results in all_results.items():
        for r in results: 
            train_str = f"{r.train_accuracy:.4f} ± {r.train_std:.4f}"
            test_str = f"{r.test_accuracy:.4f} ± {r.test_std:.4f}"
            print(f"{r.encoding_name:<22} {r.model_name:<6} {train_str:<18} {test_str:<18}")
            
            if r.test_accuracy > best_test_acc:
                best_test_acc = r.test_accuracy
                best_config = r
    
    print("-" * 75)
    if best_config:
        print(f"Best: {best_config.encoding_name} + {best_config.model_name} "
              f"= {best_test_acc:.4f} ± {best_config.test_std:.4f}")

In [19]:
def create_summary_table(all_dataset_results, 
                         model_name="SVM",
                         show_std=False) -> pd.DataFrame:
    encodings = list(ENCODING_REGISTER.keys())
    
    table_data = []
    for dataset_name, result_dict in all_dataset_results.items():
        row = {"Dataset": dataset_name}
        results = result_dict["results"]
        
        for enc_name in encodings:
            if enc_name in results:
                for r in results[enc_name]:
                    if r.model_name == model_name:
                        if show_std:
                            row[enc_name] = f"{r.test_accuracy:.4f} ± {r.test_std:.4f}"
                        else:
                            row[enc_name] = r.test_accuracy
                        break
            else:
                row[enc_name] = None if not show_std else "-"
        
        table_data.append(row)
    
    df = pd.DataFrame(table_data)
    df = df.set_index("Dataset")
    
    return df

## 4. Main Execution

Run the full evaluation pipeline across all 200 datasets. Raw `(X, y)` pairs are loaded via `ExtendedDatasetLoader`; preprocessing (PCA + scaling) is applied per-run inside `total_runs` to ensure split-specific normalization.

Results are serialized to a pickle file to avoid re-running the multi-hour evaluation.

In [ ]:
loader = ExtendedDatasetLoader(random_state=42)
raw_datasets = loader.load_all_extended(verbose=True)

print(f"Total datasets: {len(raw_datasets)}")
print("=" * 60)

all_results = {}

for dataset_name in raw_datasets.keys():
    result = total_runs(
        dataset_name=dataset_name,
        raw_datasets=raw_datasets,
        n_runs=10,
        random_state=42,
        max_qubit=4,
    )
    all_results[dataset_name] = result

print(f"\n Completely Loading datasets")

In [ ]:
import pickle

with open('all_results with load_data.pkl', 'wb') as f:
    pickle.dump(all_results, f)
print(f"Saved {len(all_results)} results to all_results with load_data.pkl")

Saved 200 results to all_results with load_data.pkl

## 5. Result Summaries

Three views of the evaluation results:
1. Best encoding circuit per classifier per dataset
2. Best overall combination (classifier + encoding circuit) per dataset
3. Side-by-side classifier comparison per dataset

In [ ]:
print("\n" + "="*80)
print("SUMMARY: BEST KERNEL FOR EACH MODEL (ACROSS ALL DATASETS)")
print("="*80)

for model_name in ["SVM", "GPC", "KRC"]:
    print(f"\n{'='*70}")
    print(f"MODEL: {model_name}")
    print(f"{'='*70}")
    print(f"{'Dataset':<25} {'Best Kernel':<22} {'Test Accuracy':<18}")
    print("-" * 70)
    
    for dataset_name, result_dict in all_results.items():
        results = result_dict["results"]
        
        best_acc = 0
        best_kernel = None
        best_std = 0
        
        for enc_name, enc_results in results.items():
            for r in enc_results:
                if r.model_name == model_name and r.test_accuracy > best_acc:
                    best_acc = r.test_accuracy
                    best_kernel = enc_name
                    best_std = r.test_std
        
        acc_str = f"{best_acc:.4f} ± {best_std:.4f}"
        print(f"{dataset_name:<25} {best_kernel:<22} {acc_str:<18}")
    
    print("-" * 70)

================================================================================
SUMMARY: BEST KERNEL FOR EACH MODEL (ACROSS ALL DATASETS)
================================================================================

======================================================================
MODEL: SVM
======================================================================
Dataset                   Best Kernel            Test Accuracy
----------------------------------------------------------------------
Blobs_F2C2_S100           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C2_S150           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C2_S200           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C3_S100           HighDim                1.0000 ± 0.0000
Blobs_F2C3_S150           HighDim                1.0000 ± 0.0000
Blobs_F2C3_S200           HighDim                1.0000 ± 0.0000
Blobs_F2C4_S100           HighDim                1.0000 ± 0.0000
Blobs_F2C4_S150           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C4_S200           HighDim                1.0000 ± 0.0000
Blobs_F3C2_S100           HZY_CZ                 1.0000 ± 0.0000
Blobs_F3C2_S150           HZY_CZ                 1.0000 ± 0.0000
Blobs_F3C2_S200           HighDim                1.0000 ± 0.0000
Blobs_F3C3_S100           HighDim                1.0000 ± 0.0000
Blobs_F3C3_S150           HighDim                1.0000 ± 0.0000
Blobs_F3C3_S200           HighDim                1.0000 ± 0.0000
Blobs_F4C2_S100           HighDim                1.0000 ± 0.0000
Blobs_F4C2_S150           HighDim                1.0000 ± 0.0000
Blobs_F4C2_S200           HighDim                1.0000 ± 0.0000
Blobs_F4C3_S100           HighDim                1.0000 ± 0.0000
Blobs_F4C3_S150           HighDim                1.0000 ± 0.0000
Blobs_F4C3_S200           HighDim                1.0000 ± 0.0000
Blobs_F4C4_S100           HighDim                1.0000 ± 0.0000
Blobs_F4C4_S150           HighDim                1.0000 ± 0.0000
Blobs_F4C4_S200           HighDim                1.0000 ± 0.0000
Blobs_hard_F2C2_std1.5_S100 HZY_CZ                 0.9950 ± 0.0150
Blobs_hard_F2C2_std1.5_S150 HighDim                0.9967 ± 0.0100
Blobs_hard_F2C2_std1.5_S200 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std2.0_S100 HZY_CZ                 0.9950 ± 0.0150
Blobs_hard_F2C2_std2.0_S150 HighDim                0.9967 ± 0.0100
Blobs_hard_F2C2_std2.0_S200 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C3_std2.0_S100 HZY_CZ                 0.9850 ± 0.0229
Blobs_hard_F2C3_std2.0_S150 HZY_CZ                 0.9833 ± 0.0307
Blobs_hard_F2C3_std2.0_S200 HZY_CZ                 0.9975 ± 0.0075
Blobs_hard_F3C2_std2.0_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F3C2_std2.0_S150 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F3C2_std2.0_S200 HighDim                1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S150 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S200 HighDim                1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S150 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S200 HighDim                1.0000 ± 0.0000
Circle_n5pct_f3_S100      HighDim                1.0000 ± 0.0000
Circle_n5pct_f3_S150      HighDim                1.0000 ± 0.0000
Circle_n5pct_f3_S200      HighDim                1.0000 ± 0.0000
Circle_n5pct_f5_S100      SeparableRX            1.0000 ± 0.0000
Circle_n5pct_f5_S150      HZY_CZ                 1.0000 ± 0.0000
Circle_n5pct_f5_S200      SeparableRX            1.0000 ± 0.0000
Circle_n10pct_f5_S100     HardwareEfficientRx    0.9850 ± 0.0229
Circle_n10pct_f5_S150     SeparableRX            1.0000 ± 0.0000
Circle_n10pct_f5_S200     SeparableRX            0.9875 ± 0.0168
Circle_n10pct_f7_S100     ZFeatureMap            0.9000 ± 0.0632
Circle_n10pct_f7_S150     ZFeatureMap            0.9400 ± 0.0389
Circle_n10pct_f7_S200     HardwareEfficientRx    0.9225 ± 0.0410
Circle_n15pct_f5_S100     SeparableRX            0.9450 ± 0.0472
Circle_n15pct_f5_S150     SeparableRX            0.9700 ± 0.0314
Circle_n15pct_f5_S200     HardwareEfficientRx    0.9475 ± 0.0305
Circle_n15pct_f8_S100     ZFeatureMap            0.7000 ± 0.1183
Circle_n15pct_f8_S150     HardwareEfficientRx    0.7100 ± 0.0761
Circle_n15pct_f8_S200     ZFeatureMap            0.7300 ± 0.0687
Circle_n20pct_f5_S100     SeparableRX            0.8800 ± 0.0400
Circle_n20pct_f5_S150     ZFeatureMap            0.8833 ± 0.0477
Circle_n20pct_f5_S200     SeparableRX            0.8900 ± 0.0477
Circle_n20pct_f7_S100     ZFeatureMap            0.7250 ± 0.0929
Circle_n20pct_f7_S150     HardwareEfficientRx    0.7467 ± 0.0653
Circle_n20pct_f7_S200     ZFeatureMap            0.7650 ± 0.0561
Moons_n5pct_S100          HighDim                0.9800 ± 0.0245
Moons_n5pct_S150          HighDim                0.9900 ± 0.0213
Moons_n5pct_S200          ZFeatureMap            0.9950 ± 0.0150
Moons_n10pct_S100         HighDim                0.9600 ± 0.0436
Moons_n10pct_S150         HighDim                0.9933 ± 0.0133
Moons_n10pct_S200         HighDim                0.9825 ± 0.0160
Moons_n15pct_S100         HighDim                0.9300 ± 0.0458
Moons_n15pct_S150         HighDim                0.9667 ± 0.0394
Moons_n15pct_S200         HighDim                0.9675 ± 0.0225
Moons_n20pct_S100         HighDim                0.9300 ± 0.0510
Moons_n20pct_S150         HighDim                0.9233 ± 0.0539
Moons_n20pct_S200         HighDim                0.9450 ± 0.0332
Moons_n25pct_S100         HighDim                0.9100 ± 0.0436
Moons_n25pct_S150         HighDim                0.8667 ± 0.0730
Moons_n25pct_S200         HighDim                0.9075 ± 0.0419
Moons_n30pct_S100         HighDim                0.8900 ± 0.0539
Moons_n30pct_S150         HighDim                0.8300 ± 0.0781
Moons_n30pct_S200         HighDim                0.8800 ± 0.0367
Moons_n35pct_S100         HighDim                0.8850 ± 0.0550
Moons_n35pct_S150         HighDim                0.8233 ± 0.0775
Moons_n35pct_S200         HighDim                0.8575 ± 0.0488
Rings_3r_n5pct_S100       ZFeatureMap            0.9950 ± 0.0150
Rings_3r_n5pct_S150       ZFeatureMap            0.9900 ± 0.0300
Rings_3r_n5pct_S200       ZFeatureMap            1.0000 ± 0.0000
Rings_3r_n10pct_S100      ZFeatureMap            0.9800 ± 0.0245
Rings_3r_n10pct_S150      ZFeatureMap            0.9800 ± 0.0340
Rings_3r_n10pct_S200      ZFeatureMap            0.9975 ± 0.0075
Rings_3r_n20pct_S100      ZFeatureMap            0.9300 ± 0.0557
Rings_3r_n20pct_S150      ZFeatureMap            0.9533 ± 0.0452
Rings_3r_n20pct_S200      ZFeatureMap            0.9675 ± 0.0251
Rings_4r_n5pct_S100       ZFeatureMap            0.7350 ± 0.0867
Rings_4r_n5pct_S150       ZFeatureMap            0.7367 ± 0.0526
Rings_4r_n5pct_S200       ZZFeatureMap           0.7300 ± 0.0723
Rings_4r_n10pct_S100      ZZFeatureMap           0.7200 ± 0.1030
Rings_4r_n10pct_S150      ZZFeatureMap           0.6967 ± 0.0795
Rings_4r_n10pct_S200      ZZFeatureMap           0.7050 ± 0.0660
Rings_4r_n15pct_S100      ZZFeatureMap           0.7250 ± 0.0955
Rings_4r_n15pct_S150      ZZFeatureMap           0.6700 ± 0.0823
Rings_4r_n15pct_S200      ZZFeatureMap           0.6975 ± 0.0637
Rings_5r_n10pct_S100      ParamZFeatureMap       0.5850 ± 0.0867
Rings_5r_n10pct_S150      ZFeatureMap            0.6700 ± 0.0547
Rings_5r_n10pct_S200      ZZFeatureMap           0.6725 ± 0.0711
Rings_5r_n15pct_S100      Chebyshev              0.5900 ± 0.0583
Rings_5r_n15pct_S150      ZFeatureMap            0.6567 ± 0.0633
Rings_5r_n15pct_S200      ZZFeatureMap           0.6725 ± 0.0564
XOR_S100                  HardwareEfficientRx    0.9450 ± 0.0415
XOR_S150                  HighDim                0.9367 ± 0.0526
XOR_S200                  HighDim                0.9650 ± 0.0122
XOR_n5pct_S100            HardwareEfficientRx    0.9400 ± 0.0436
XOR_n5pct_S150            HighDim                0.9467 ± 0.0427
XOR_n5pct_S200            HighDim                0.9675 ± 0.0160
XOR_n10pct_S100           HZY_CZ                 0.9400 ± 0.0436
XOR_n10pct_S150           HardwareEfficientRx    0.9433 ± 0.0517
XOR_n10pct_S200           HighDim                0.9650 ± 0.0200
XOR_n15pct_S100           HighDim                0.9200 ± 0.0714
XOR_n15pct_S150           HardwareEfficientRx    0.9300 ± 0.0623
XOR_n15pct_S200           HighDim                0.9650 ± 0.0339
XOR_n20pct_S100           HighDim                0.9350 ± 0.0502
XOR_n20pct_S150           HZY_CZ                 0.9267 ± 0.0593
XOR_n20pct_S200           HighDim                0.9700 ± 0.0292
XOR_n25pct_S100           HighDim                0.9250 ± 0.0512
XOR_n25pct_S150           HardwareEfficientRx    0.9200 ± 0.0562
XOR_n25pct_S200           HighDim                0.9700 ± 0.0292
Spiral_S100               ZZFeatureMap           0.5900 ± 0.1411
Spiral_S150               ZZFeatureMap           0.6667 ± 0.0422
Spiral_S200               ZZFeatureMap           0.6475 ± 0.0518
Spiral_n5pct_S100         ZZFeatureMap           0.6400 ± 0.1562
Spiral_n5pct_S150         ZZFeatureMap           0.6200 ± 0.0581
Spiral_n5pct_S200         ZZFeatureMap           0.6850 ± 0.0391
Spiral_n10pct_S100        ZZFeatureMap           0.6750 ± 0.1647
Spiral_n10pct_S150        ZZFeatureMap           0.6267 ± 0.0696
Spiral_n10pct_S200        ZZFeatureMap           0.6775 ± 0.0666
Spiral_n15pct_S100        ZZFeatureMap           0.6800 ± 0.1435
Spiral_n15pct_S150        HZY_CZ                 0.5900 ± 0.0667
Spiral_n15pct_S200        HZY_CZ                 0.6350 ± 0.0539
Spiral_n20pct_S100        ZZFeatureMap           0.6500 ± 0.1140
Spiral_n20pct_S150        HZY_CZ                 0.5700 ± 0.0994
Spiral_n20pct_S200        HZY_CZ                 0.6350 ± 0.0604
Spiral_n25pct_S100        ZZFeatureMap           0.6450 ± 0.1193
Spiral_n25pct_S150        ParamZFeatureMap       0.5833 ± 0.0792
Spiral_n25pct_S200        SeparableRX            0.6225 ± 0.0575
Checkerboard_2x2_S100     HighDim                0.9450 ± 0.0472
Checkerboard_2x2_S150     HardwareEfficientRx    0.9267 ± 0.0327
Checkerboard_2x2_S200     HighDim                0.9550 ± 0.0245
Checkerboard_2x2_n5pct_S100 HighDim                0.9150 ± 0.0320
Checkerboard_2x2_n5pct_S150 HighDim                0.8967 ± 0.0547
Checkerboard_2x2_n5pct_S200 HighDim                0.9450 ± 0.0332
Checkerboard_2x2_n10pct_S100 HighDim                0.8800 ± 0.0458
Checkerboard_2x2_n10pct_S150 HighDim                0.8800 ± 0.0499
Checkerboard_2x2_n10pct_S200 HighDim                0.9350 ± 0.0278
Checkerboard_3x3_S100     ZFeatureMap            0.8800 ± 0.0640
Checkerboard_3x3_S150     ZFeatureMap            0.8933 ± 0.0533
Checkerboard_3x3_S200     ZFeatureMap            0.9275 ± 0.0344
Checkerboard_3x3_n5pct_S100 SeparableRX            0.8550 ± 0.0850
Checkerboard_3x3_n5pct_S150 ZFeatureMap            0.8800 ± 0.0718
Checkerboard_3x3_n5pct_S200 ZFeatureMap            0.8900 ± 0.0572
Checkerboard_3x3_n10pct_S100 SeparableRX            0.8500 ± 0.0775
Checkerboard_3x3_n10pct_S150 ZFeatureMap            0.8267 ± 0.0917
Checkerboard_3x3_n10pct_S200 ZFeatureMap            0.7950 ± 0.0620
Checkerboard_4x4_S100     HighDim                0.7000 ± 0.0632
Checkerboard_4x4_S150     ZFeatureMap            0.6667 ± 0.0760
Checkerboard_4x4_S200     ZFeatureMap            0.7150 ± 0.0867
Checkerboard_4x4_n5pct_S100 HighDim                0.6550 ± 0.1150
Checkerboard_4x4_n5pct_S150 ZFeatureMap            0.6667 ± 0.0683
Checkerboard_4x4_n5pct_S200 ZFeatureMap            0.7575 ± 0.0922
Checkerboard_5x5_S100     ZFeatureMap            0.6500 ± 0.0975
Checkerboard_5x5_S150     ZFeatureMap            0.6833 ± 0.0734
Checkerboard_5x5_S200     SeparableRX            0.6525 ± 0.0506
Iris                      HighDim                1.0000 ± 0.0000
Wine                      HardwareEfficientRx    0.9808 ± 0.0258
BreastCancer              SeparableRX            0.9447 ± 0.0167
Pima                      SeparableRX            0.7461 ± 0.0249
Banknote                  HardwareEfficientRx    1.0000 ± 0.0000
Haberman                  ParamZFeatureMap       0.7500 ± 0.0108
BreastCancer_S80          SeparableRX            0.9563 ± 0.0400
BreastCancer_S100         SeparableRX            0.9600 ± 0.0300
BreastCancer_S120         HardwareEfficientRx    0.9500 ± 0.0520
BreastCancer_S150         HighDim                0.9733 ± 0.0249
Pima_S80                  HardwareEfficientRx    0.6937 ± 0.0653
Pima_S100                 HardwareEfficientRx    0.7450 ± 0.0850
Pima_S120                 HardwareEfficientRx    0.8125 ± 0.0678
Pima_S150                 HardwareEfficientRx    0.7667 ± 0.0615
Banknote_S80              SeparableRX            0.9875 ± 0.0250
Banknote_S100             SeparableRX            0.9700 ± 0.0400
Banknote_S120             HardwareEfficientRx    0.9917 ± 0.0167
Banknote_S150             HardwareEfficientRx    0.9733 ± 0.0249
Haberman_S80              SeparableRX            0.8250 ± 0.0875
Haberman_S100             ZFeatureMap            0.7950 ± 0.0610
Haberman_S120             ZFeatureMap            0.8250 ± 0.0520
Haberman_S150             ZFeatureMap            0.8167 ± 0.0373
Wine_S80                  HardwareEfficientRx    0.9812 ± 0.0286
Wine_S100                 HardwareEfficientRx    0.9550 ± 0.0610
Wine_S120                 HardwareEfficientRx    0.9792 ± 0.0280
Iris_S80                  HighDim                1.0000 ± 0.0000
----------------------------------------------------------------------

======================================================================
MODEL: GPC
======================================================================
Dataset                   Best Kernel            Test Accuracy
----------------------------------------------------------------------
Blobs_F2C2_S100           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C2_S150           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C2_S200           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C3_S100           HighDim                1.0000 ± 0.0000
Blobs_F2C3_S150           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C3_S200           HighDim                1.0000 ± 0.0000
Blobs_F2C4_S100           HighDim                1.0000 ± 0.0000
Blobs_F2C4_S150           HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C4_S200           HighDim                1.0000 ± 0.0000
Blobs_F3C2_S100           HZY_CZ                 1.0000 ± 0.0000
Blobs_F3C2_S150           HZY_CZ                 1.0000 ± 0.0000
Blobs_F3C2_S200           HZY_CZ                 1.0000 ± 0.0000
Blobs_F3C3_S100           HighDim                1.0000 ± 0.0000
Blobs_F3C3_S150           HighDim                1.0000 ± 0.0000
Blobs_F3C3_S200           HighDim                1.0000 ± 0.0000
Blobs_F4C2_S100           HighDim                1.0000 ± 0.0000
Blobs_F4C2_S150           HighDim                1.0000 ± 0.0000
Blobs_F4C2_S200           HighDim                1.0000 ± 0.0000
Blobs_F4C3_S100           HighDim                1.0000 ± 0.0000
Blobs_F4C3_S150           HighDim                1.0000 ± 0.0000
Blobs_F4C3_S200           HighDim                1.0000 ± 0.0000
Blobs_F4C4_S100           HighDim                1.0000 ± 0.0000
Blobs_F4C4_S150           HighDim                1.0000 ± 0.0000
Blobs_F4C4_S200           HighDim                1.0000 ± 0.0000
Blobs_hard_F2C2_std1.5_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std1.5_S150 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std1.5_S200 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std2.0_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std2.0_S150 HZY_CZ                 0.9967 ± 0.0100
Blobs_hard_F2C2_std2.0_S200 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C3_std2.0_S100 HZY_CZ                 0.9850 ± 0.0229
Blobs_hard_F2C3_std2.0_S150 HZY_CZ                 0.9900 ± 0.0213
Blobs_hard_F2C3_std2.0_S200 HZY_CZ                 0.9975 ± 0.0075
Blobs_hard_F3C2_std2.0_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F3C2_std2.0_S150 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F3C2_std2.0_S200 HZY_CZ                 0.9975 ± 0.0075
Blobs_hard_F4C2_std2.0_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S150 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S200 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S100 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S150 HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S200 HZY_CZ                 1.0000 ± 0.0000
Circle_n5pct_f3_S100      SeparableRX            1.0000 ± 0.0000
Circle_n5pct_f3_S150      HighDim                1.0000 ± 0.0000
Circle_n5pct_f3_S200      HighDim                1.0000 ± 0.0000
Circle_n5pct_f5_S100      SeparableRX            1.0000 ± 0.0000
Circle_n5pct_f5_S150      SeparableRX            1.0000 ± 0.0000
Circle_n5pct_f5_S200      SeparableRX            1.0000 ± 0.0000
Circle_n10pct_f5_S100     ZFeatureMap            0.9800 ± 0.0458
Circle_n10pct_f5_S150     SeparableRX            1.0000 ± 0.0000
Circle_n10pct_f5_S200     SeparableRX            0.9875 ± 0.0168
Circle_n10pct_f7_S100     ZFeatureMap            0.9150 ± 0.0594
Circle_n10pct_f7_S150     ZFeatureMap            0.9433 ± 0.0300
Circle_n10pct_f7_S200     ZFeatureMap            0.9150 ± 0.0406
Circle_n15pct_f5_S100     ZFeatureMap            0.9300 ± 0.0510
Circle_n15pct_f5_S150     SeparableRX            0.9633 ± 0.0379
Circle_n15pct_f5_S200     SeparableRX            0.9450 ± 0.0400
Circle_n15pct_f8_S100     ZFeatureMap            0.7150 ± 0.1001
Circle_n15pct_f8_S150     ZFeatureMap            0.6967 ± 0.0752
Circle_n15pct_f8_S200     ZFeatureMap            0.7350 ± 0.0673
Circle_n20pct_f5_S100     SeparableRX            0.8900 ± 0.0490
Circle_n20pct_f5_S150     ZFeatureMap            0.8933 ± 0.0467
Circle_n20pct_f5_S200     SeparableRX            0.8900 ± 0.0464
Circle_n20pct_f7_S100     ZFeatureMap            0.7400 ± 0.0889
Circle_n20pct_f7_S150     ZFeatureMap            0.7500 ± 0.0522
Circle_n20pct_f7_S200     ZFeatureMap            0.7675 ± 0.0690
Moons_n5pct_S100          HighDim                0.9450 ± 0.0522
Moons_n5pct_S150          ZFeatureMap            0.9700 ± 0.0277
Moons_n5pct_S200          ZFeatureMap            0.9875 ± 0.0168
Moons_n10pct_S100         ZFeatureMap            0.9400 ± 0.0374
Moons_n10pct_S150         HighDim                0.9533 ± 0.0306
Moons_n10pct_S200         ZFeatureMap            0.9650 ± 0.0229
Moons_n15pct_S100         HighDim                0.9300 ± 0.0458
Moons_n15pct_S150         HighDim                0.9500 ± 0.0307
Moons_n15pct_S200         HighDim                0.9375 ± 0.0202
Moons_n20pct_S100         HighDim                0.9100 ± 0.0374
Moons_n20pct_S150         HighDim                0.9100 ± 0.0473
Moons_n20pct_S200         HighDim                0.9250 ± 0.0296
Moons_n25pct_S100         HighDim                0.8950 ± 0.0472
Moons_n25pct_S150         HighDim                0.8767 ± 0.0633
Moons_n25pct_S200         HighDim                0.8950 ± 0.0384
Moons_n30pct_S100         HighDim                0.8800 ± 0.0510
Moons_n30pct_S150         HighDim                0.8400 ± 0.0742
Moons_n30pct_S200         HighDim                0.8750 ± 0.0403
Moons_n35pct_S100         HighDim                0.8850 ± 0.0550
Moons_n35pct_S150         HighDim                0.8267 ± 0.0712
Moons_n35pct_S200         HighDim                0.8575 ± 0.0501
Rings_3r_n5pct_S100       ZFeatureMap            0.9200 ± 0.0748
Rings_3r_n5pct_S150       ZFeatureMap            0.9433 ± 0.0496
Rings_3r_n5pct_S200       ZFeatureMap            0.9675 ± 0.0297
Rings_3r_n10pct_S100      ZFeatureMap            0.9100 ± 0.0663
Rings_3r_n10pct_S150      ZFeatureMap            0.9267 ± 0.0593

In [ ]:
print("\n" + "="*80)
print("SUMMARY: BEST MODEL + KERNEL FOR EACH DATASET")
print("="*80)
print(f"{'Dataset':<25} {'Best Model':<8} {'Best Kernel':<22} {'Test Accuracy':<18}")
print("-" * 80)

for dataset_name, result_dict in all_results.items():
    results = result_dict["results"]
    
    best_acc = 0
    best_kernel = None
    best_model = None
    best_std = 0
    
    for enc_name, enc_results in results.items():
        for r in enc_results:
            if r.test_accuracy > best_acc:
                best_acc = r.test_accuracy
                best_kernel = enc_name
                best_model = r.model_name
                best_std = r.test_std
    
    acc_str = f"{best_acc:.4f} ± {best_std:.4f}"
    print(f"{dataset_name:<25} {best_model:<8} {best_kernel:<22} {acc_str:<18}")

print("-" * 80)

================================================================================
SUMMARY: BEST MODEL + KERNEL FOR EACH DATASET
================================================================================
Dataset                   Best Model Best Kernel            Test Accuracy
--------------------------------------------------------------------------------
Blobs_F2C2_S100           SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C2_S150           SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C2_S200           SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C3_S100           SVM      HighDim                1.0000 ± 0.0000
Blobs_F2C3_S150           SVM      HighDim                1.0000 ± 0.0000
Blobs_F2C3_S200           SVM      HighDim                1.0000 ± 0.0000
Blobs_F2C4_S100           SVM      HighDim                1.0000 ± 0.0000
Blobs_F2C4_S150           SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_F2C4_S200           SVM      HighDim                1.0000 ± 0.0000
Blobs_F3C2_S100           SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_F3C2_S150           SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_F3C2_S200           SVM      HighDim                1.0000 ± 0.0000
Blobs_F3C3_S100           SVM      HighDim                1.0000 ± 0.0000
Blobs_F3C3_S150           SVM      HighDim                1.0000 ± 0.0000
Blobs_F3C3_S200           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C2_S100           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C2_S150           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C2_S200           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C3_S100           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C3_S150           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C3_S200           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C4_S100           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C4_S150           SVM      HighDim                1.0000 ± 0.0000
Blobs_F4C4_S200           SVM      HighDim                1.0000 ± 0.0000
Blobs_hard_F2C2_std1.5_S100 GPC      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std1.5_S150 GPC      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std1.5_S200 SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std2.0_S100 GPC      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C2_std2.0_S150 SVM      HighDim                0.9967 ± 0.0100
Blobs_hard_F2C2_std2.0_S200 SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F2C3_std2.0_S100 SVM      HZY_CZ                 0.9850 ± 0.0229
Blobs_hard_F2C3_std2.0_S150 GPC      HZY_CZ                 0.9900 ± 0.0213
Blobs_hard_F2C3_std2.0_S200 SVM      HZY_CZ                 0.9975 ± 0.0075
Blobs_hard_F3C2_std2.0_S100 SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F3C2_std2.0_S150 KRC      HighDim                1.0000 ± 0.0000
Blobs_hard_F3C2_std2.0_S200 SVM      HighDim                1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S100 SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S150 SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.0_S200 SVM      HighDim                1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S100 SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S150 SVM      HZY_CZ                 1.0000 ± 0.0000
Blobs_hard_F4C2_std2.5_S200 SVM      HighDim                1.0000 ± 0.0000
Circle_n5pct_f3_S100      SVM      HighDim                1.0000 ± 0.0000
Circle_n5pct_f3_S150      SVM      HighDim                1.0000 ± 0.0000
Circle_n5pct_f3_S200      SVM      HighDim                1.0000 ± 0.0000
Circle_n5pct_f5_S100      SVM      SeparableRX            1.0000 ± 0.0000
Circle_n5pct_f5_S150      SVM      HZY_CZ                 1.0000 ± 0.0000
Circle_n5pct_f5_S200      SVM      SeparableRX            1.0000 ± 0.0000
Circle_n10pct_f5_S100     SVM      HardwareEfficientRx    0.9850 ± 0.0229
Circle_n10pct_f5_S150     SVM      SeparableRX            1.0000 ± 0.0000
Circle_n10pct_f5_S200     SVM      SeparableRX            0.9875 ± 0.0168
Circle_n10pct_f7_S100     KRC      ZFeatureMap            0.9200 ± 0.0557
Circle_n10pct_f7_S150     KRC      ZFeatureMap            0.9467 ± 0.0306
Circle_n10pct_f7_S200     SVM      HardwareEfficientRx    0.9225 ± 0.0410
Circle_n15pct_f5_S100     SVM      SeparableRX            0.9450 ± 0.0472
Circle_n15pct_f5_S150     SVM      SeparableRX            0.9700 ± 0.0314
Circle_n15pct_f5_S200     SVM      HardwareEfficientRx    0.9475 ± 0.0305
Circle_n15pct_f8_S100     GPC      ZFeatureMap            0.7150 ± 0.1001
Circle_n15pct_f8_S150     KRC      HardwareEfficientRx    0.7200 ± 0.0763
Circle_n15pct_f8_S200     GPC      ZFeatureMap            0.7350 ± 0.0673
Circle_n20pct_f5_S100     GPC      SeparableRX            0.8900 ± 0.0490
Circle_n20pct_f5_S150     GPC      ZFeatureMap            0.8933 ± 0.0467
Circle_n20pct_f5_S200     SVM      SeparableRX            0.8900 ± 0.0477
Circle_n20pct_f7_S100     GPC      ZFeatureMap            0.7400 ± 0.0889
Circle_n20pct_f7_S150     KRC      HardwareEfficientRx    0.7533 ± 0.0600
Circle_n20pct_f7_S200     GPC      ZFeatureMap            0.7675 ± 0.0690
Moons_n5pct_S100          SVM      HighDim                0.9800 ± 0.0245
Moons_n5pct_S150          SVM      HighDim                0.9900 ± 0.0213
Moons_n5pct_S200          SVM      ZFeatureMap            0.9950 ± 0.0150
Moons_n10pct_S100         SVM      HighDim                0.9600 ± 0.0436
Moons_n10pct_S150         SVM      HighDim                0.9933 ± 0.0133
Moons_n10pct_S200         SVM      HighDim                0.9825 ± 0.0160
Moons_n15pct_S100         KRC      HighDim                0.9350 ± 0.0391
Moons_n15pct_S150         SVM      HighDim                0.9667 ± 0.0394
Moons_n15pct_S200         KRC      HighDim                0.9700 ± 0.0245
Moons_n20pct_S100         SVM      HighDim                0.9300 ± 0.0510
Moons_n20pct_S150         KRC      HighDim                0.9333 ± 0.0516
Moons_n20pct_S200         KRC      HighDim                0.9500 ± 0.0354
Moons_n25pct_S100         KRC      HighDim                0.9200 ± 0.0458
Moons_n25pct_S150         KRC      HighDim                0.8900 ± 0.0651
Moons_n25pct_S200         KRC      HighDim                0.9175 ± 0.0336
Moons_n30pct_S100         KRC      HighDim                0.9000 ± 0.0387
Moons_n30pct_S150         GPC      HighDim                0.8400 ± 0.0742
Moons_n30pct_S200         SVM      HighDim                0.8800 ± 0.0367
Moons_n35pct_S100         KRC      HighDim                0.8900 ± 0.0539
Moons_n35pct_S150         GPC      HighDim                0.8267 ± 0.0712
Moons_n35pct_S200         KRC      HighDim                0.8600 ± 0.0436
Rings_3r_n5pct_S100       SVM      ZFeatureMap            0.9950 ± 0.0150
Rings_3r_n5pct_S150       KRC      ZFeatureMap            0.9967 ± 0.0100
Rings_3r_n5pct_S200       SVM      ZFeatureMap            1.0000 ± 0.0000
Rings_3r_n10pct_S100      KRC      ZFeatureMap            0.9900 ± 0.0200
Rings_3r_n10pct_S150      KRC      ZFeatureMap            0.9967 ± 0.0100
Rings_3r_n10pct_S200      SVM      ZFeatureMap            0.9975 ± 0.0075
Rings_3r_n20pct_S100      KRC      ZFeatureMap            0.9600 ± 0.0300
Rings_3r_n20pct_S150      SVM      ZFeatureMap            0.9533 ± 0.0452
Rings_3r_n20pct_S200      KRC      ZFeatureMap            0.9725 ± 0.0236
Rings_4r_n5pct_S100       SVM      ZFeatureMap            0.7350 ± 0.0867
Rings_4r_n5pct_S150       SVM      ZFeatureMap            0.7367 ± 0.0526
Rings_4r_n5pct_S200       SVM      ZZFeatureMap           0.7300 ± 0.0723
Rings_4r_n10pct_S100      SVM      ZZFeatureMap           0.7200 ± 0.1030
Rings_4r_n10pct_S150      KRC      ZZFeatureMap           0.7067 ± 0.0940
Rings_4r_n10pct_S200      SVM      ZZFeatureMap           0.7050 ± 0.0660
Rings_4r_n15pct_S100      SVM      ZZFeatureMap           0.7250 ± 0.0955
Rings_4r_n15pct_S150      KRC      ZFeatureMap            0.6867 ± 0.0957
Rings_4r_n15pct_S200      SVM      ZZFeatureMap           0.6975 ± 0.0637
Rings_5r_n10pct_S100      GPC      ParamZFeatureMap       0.5950 ± 0.0850
Rings_5r_n10pct_S150      SVM      ZFeatureMap            0.6700 ± 0.0547
Rings_5r_n10pct_S200      SVM      ZZFeatureMap           0.6725 ± 0.0711
Rings_5r_n15pct_S100      SVM      Chebyshev              0.5900 ± 0.0583
Rings_5r_n15pct_S150      SVM      ZFeatureMap            0.6567 ± 0.0633
Rings_5r_n15pct_S200      SVM      ZZFeatureMap           0.6725 ± 0.0564
XOR_S100                  SVM      HardwareEfficientRx    0.9450 ± 0.0415
XOR_S150                  KRC      HighDim                0.9433 ± 0.0616
XOR_S200                  GPC      HighDim                0.9650 ± 0.0200
XOR_n5pct_S100            GPC      HardwareEfficientRx    0.9450 ± 0.0350
XOR_n5pct_S150            SVM      HighDim                0.9467 ± 0.0427
XOR_n5pct_S200            KRC      HZY_CZ                 0.9700 ± 0.0245
XOR_n10pct_S100           SVM      HZY_CZ                 0.9400 ± 0.0436
XOR_n10pct_S150           SVM      HardwareEfficientRx    0.9433 ± 0.0517
XOR_n10pct_S200           SVM      HighDim                0.9650 ± 0.0200
XOR_n15pct_S100           KRC      HighDim                0.9350 ± 0.0673
XOR_n15pct_S150           GPC      HardwareEfficientRx    0.9367 ± 0.0640
XOR_n15pct_S200           SVM      HighDim                0.9650 ± 0.0339
XOR_n20pct_S100           SVM      HighDim                0.9350 ± 0.0502
XOR_n20pct_S150           KRC      HZY_CZ                 0.9300 ± 0.0526
XOR_n20pct_S200           SVM      HighDim                0.9700 ± 0.0292
XOR_n25pct_S100           SVM      HighDim                0.9250 ± 0.0512
XOR_n25pct_S150           GPC      HZY_CZ                 0.9233 ± 0.0396
XOR_n25pct_S200           SVM      HighDim                0.9700 ± 0.0292
Spiral_S100               KRC      ZZFeatureMap           0.6200 ± 0.1269
Spiral_S150               KRC      ZZFeatureMap           0.6833 ± 0.0401
Spiral_S200               KRC      ZFeatureMap            0.6600 ± 0.0357
Spiral_n5pct_S100         KRC      ZZFeatureMap           0.6500 ± 0.1245
Spiral_n5pct_S150         KRC      ZZFeatureMap           0.6533 ± 0.0476
Spiral_n5pct_S200         SVM      ZZFeatureMap           0.6850 ± 0.0391
Spiral_n10pct_S100        SVM      ZZFeatureMap           0.6750 ± 0.1647
Spiral_n10pct_S150        KRC      ZFeatureMap            0.6567 ± 0.0633
Spiral_n10pct_S200        KRC      ZZFeatureMap           0.6800 ± 0.0400
Spiral_n15pct_S100        KRC      ZZFeatureMap           0.6900 ± 0.1241
Spiral_n15pct_S150        KRC      ZFeatureMap            0.5967 ± 0.0623
Spiral_n15pct_S200        KRC      ZZFeatureMap           0.6400 ± 0.0682
Spiral_n20pct_S100        KRC      ZZFeatureMap           0.6800 ± 0.1249
Spiral_n20pct_S150        SVM      HZY_CZ                 0.5700 ± 0.0994
Spiral_n20pct_S200        SVM      HZY_CZ                 0.6350 ± 0.0604
Spiral_n25pct_S100        KRC      ZZFeatureMap           0.6650 ± 0.1415
Spiral_n25pct_S150        SVM      ParamZFeatureMap       0.5833 ± 0.0792
Spiral_n25pct_S200        SVM      SeparableRX            0.6225 ± 0.0575
Checkerboard_2x2_S100     SVM      HighDim                0.9450 ± 0.0472
Checkerboard_2x2_S150     SVM      HardwareEfficientRx    0.9267 ± 0.0327
Checkerboard_2x2_S200     SVM      HighDim                0.9550 ± 0.0245
Checkerboard_2x2_n5pct_S100 KRC      SeparableRX            0.9250 ± 0.0642
Checkerboard_2x2_n5pct_S150 KRC      HighDim                0.9033 ± 0.0458
Checkerboard_2x2_n5pct_S200 KRC      HighDim                0.9475 ± 0.0305
Checkerboard_2x2_n10pct_S100 GPC      HardwareEfficientRx    0.8900 ± 0.0583
Checkerboard_2x2_n10pct_S150 SVM      HighDim                0.8800 ± 0.0499
Checkerboard_2x2_n10pct_S200 SVM      HighDim                0.9350 ± 0.0278
Checkerboard_3x3_S100     KRC      ZFeatureMap            0.9000 ± 0.0837
Checkerboard_3x3_S150     KRC      ZFeatureMap            0.9233 ± 0.0616
Checkerboard_3x3_S200     KRC      ZFeatureMap            0.9400 ± 0.0255
Checkerboard_3x3_n5pct_S100 GPC      ZFeatureMap            0.8700 ± 0.0640
Checkerboard_3x3_n5pct_S150 KRC      ZFeatureMap            0.8900 ± 0.0761
Checkerboard_3x3_n5pct_S200 KRC      ZFeatureMap            0.9025 ± 0.0394
Checkerboard_3x3_n10pct_S100 SVM      SeparableRX            0.8500 ± 0.0775
Checkerboard_3x3_n10pct_S150 KRC      ZFeatureMap            0.8533 ± 0.0581
Checkerboard_3x3_n10pct_S200 KRC      ZFeatureMap            0.8200 ± 0.0589
Checkerboard_4x4_S100     KRC      ZFeatureMap            0.7200 ± 0.1030
Checkerboard_4x4_S150     KRC      ZFeatureMap            0.7767 ± 0.0746
Checkerboard_4x4_S200     KRC      ZFeatureMap            0.8250 ± 0.0837
Checkerboard_4x4_n5pct_S100 KRC      ZFeatureMap            0.6800 ± 0.1122
Checkerboard_4x4_n5pct_S150 KRC      ZFeatureMap            0.7367 ± 0.0706
Checkerboard_4x4_n5pct_S200 KRC      ZFeatureMap            0.8600 ± 0.0823
Checkerboard_5x5_S100     KRC      ZFeatureMap            0.7250 ± 0.0783
Checkerboard_5x5_S150     KRC      ZFeatureMap            0.7200 ± 0.0542
Checkerboard_5x5_S200     KRC      ZFeatureMap            0.6900 ± 0.1007
Iris                      SVM      HighDim                1.0000 ± 0.0000
Wine                      SVM      HardwareEfficientRx    0.9808 ± 0.0258
BreastCancer              KRC      HardwareEfficientRx    0.9465 ± 0.0177
Pima                      SVM      SeparableRX            0.7461 ± 0.0249
Banknote                  SVM      HardwareEfficientRx    1.0000 ± 0.0000
Haberman                  SVM      ParamZFeatureMap       0.7500 ± 0.0108
BreastCancer_S80          SVM      SeparableRX            0.9563 ± 0.0400
BreastCancer_S100         SVM      SeparableRX            0.9600 ± 0.0300
BreastCancer_S120         GPC      HardwareEfficientRx    0.9542 ± 0.0435
BreastCancer_S150         KRC      HighDim                0.9800 ± 0.0267
Pima_S80                  GPC      HardwareEfficientRx    0.7188 ± 0.0640
Pima_S100                 GPC      HardwareEfficientRx    0.7550 ± 0.0687
Pima_S120                 GPC      HardwareEfficientRx    0.8167 ± 0.0624
Pima_S150                 GPC      HardwareEfficientRx    0.7800 ± 0.0670
Banknote_S80              SVM      SeparableRX            0.9875 ± 0.0250
Banknote_S100             SVM      SeparableRX            0.9700 ± 0.0400
Banknote_S120             SVM      HardwareEfficientRx    0.9917 ± 0.0167
Banknote_S150             SVM      HardwareEfficientRx    0.9733 ± 0.0249
Haberman_S80              KRC      SeparableRX            0.8438 ± 0.0803
Haberman_S100             GPC      SeparableRX            0.8050 ± 0.0472
Haberman_S120             KRC      ZFeatureMap            0.8292 ± 0.0573
Haberman_S150             SVM      ZFeatureMap            0.8167 ± 0.0373
Wine_S80                  SVM      HardwareEfficientRx    0.9812 ± 0.0286
Wine_S100                 KRC      HighDim                0.9600 ± 0.0374
Wine_S120                 SVM      HardwareEfficientRx    0.9792 ± 0.0280
Iris_S80                  SVM      HighDim                1.0000 ± 0.0000
--------------------------------------------------------------------------------

In [ ]:
print("\n" + "="*80)
print("SUMMARY: MODEL COMPARISON (SIDE-BY-SIDE)")
print("="*80)

print(f"{'Dataset':<20} ", end="")
for model in ["SVM", "GPC", "KRC"]:
    print(f"{model:<25} ", end="")
print()
print("-" * 95)

for dataset_name, result_dict in all_results.items():
    results = result_dict["results"]
    print(f"{dataset_name:<20} ", end="")
    
    for model_name in ["SVM", "GPC", "KRC"]:
        best_acc = 0
        best_kernel = None
        best_std = 0
        
        for enc_name, enc_results in results.items():
            for r in enc_results:
                if r.model_name == model_name and r.test_accuracy > best_acc:
                    best_acc = r.test_accuracy
                    best_kernel = enc_name
                    best_std = r.test_std
        
        acc_str = f"{best_acc:.4f}±{best_std:.4f}"
        print(f"{acc_str:<25} ", end="")
    
    print()

================================================================================
SUMMARY: MODEL COMPARISON (SIDE-BY-SIDE)
================================================================================
Dataset              SVM                       GPC                       KRC
-----------------------------------------------------------------------------------------------
Blobs_F2C2_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C2_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C2_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C3_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C3_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C3_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C4_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C4_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F2C4_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F3C2_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F3C2_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F3C2_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F3C3_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F3C3_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F3C3_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C2_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C2_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C2_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C3_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C3_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C3_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C4_S100      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C4_S150      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_F4C4_S200      1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F2C2_std1.5_S100 0.9950±0.0150             1.0000±0.0000             0.9950±0.0150
Blobs_hard_F2C2_std1.5_S150 0.9967±0.0100             1.0000±0.0000             0.9967±0.0100
Blobs_hard_F2C2_std1.5_S200 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F2C2_std2.0_S100 0.9950±0.0150             1.0000±0.0000             0.9900±0.0200
Blobs_hard_F2C2_std2.0_S150 0.9967±0.0100             0.9967±0.0100             0.9967±0.0100
Blobs_hard_F2C2_std2.0_S200 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F2C3_std2.0_S100 0.9850±0.0229             0.9850±0.0229             0.9850±0.0229
Blobs_hard_F2C3_std2.0_S150 0.9833±0.0307             0.9900±0.0213             0.9867±0.0221
Blobs_hard_F2C3_std2.0_S200 0.9975±0.0075             0.9975±0.0075             0.9975±0.0075
Blobs_hard_F3C2_std2.0_S100 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F3C2_std2.0_S150 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F3C2_std2.0_S200 1.0000±0.0000             0.9975±0.0075             1.0000±0.0000
Blobs_hard_F4C2_std2.0_S100 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F4C2_std2.0_S150 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F4C2_std2.0_S200 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F4C2_std2.5_S100 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F4C2_std2.5_S150 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Blobs_hard_F4C2_std2.5_S200 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n5pct_f3_S100 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n5pct_f3_S150 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n5pct_f3_S200 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n5pct_f5_S100 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n5pct_f5_S150 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n5pct_f5_S200 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n10pct_f5_S100 0.9850±0.0229             0.9800±0.0458             0.9800±0.0245
Circle_n10pct_f5_S150 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Circle_n10pct_f5_S200 0.9875±0.0168             0.9875±0.0168             0.9875±0.0125
Circle_n10pct_f7_S100 0.9000±0.0632             0.9150±0.0594             0.9200±0.0557
Circle_n10pct_f7_S150 0.9400±0.0389             0.9433±0.0300             0.9467±0.0306
Circle_n10pct_f7_S200 0.9225±0.0410             0.9150±0.0406             0.9200±0.0444
Circle_n15pct_f5_S100 0.9450±0.0472             0.9300±0.0510             0.9300±0.0510
Circle_n15pct_f5_S150 0.9700±0.0314             0.9633±0.0379             0.9633±0.0379
Circle_n15pct_f5_S200 0.9475±0.0305             0.9450±0.0400             0.9475±0.0361
Circle_n15pct_f8_S100 0.7000±0.1183             0.7150±0.1001             0.6900±0.0917
Circle_n15pct_f8_S150 0.7100±0.0761             0.6967±0.0752             0.7200±0.0763
Circle_n15pct_f8_S200 0.7300±0.0687             0.7350±0.0673             0.7275±0.0493
Circle_n20pct_f5_S100 0.8800±0.0400             0.8900±0.0490             0.8850±0.0450
Circle_n20pct_f5_S150 0.8833±0.0477             0.8933±0.0467             0.8900±0.0473
Circle_n20pct_f5_S200 0.8900±0.0477             0.8900±0.0464             0.8875±0.0491
Circle_n20pct_f7_S100 0.7250±0.0929             0.7400±0.0889             0.7300±0.0812
Circle_n20pct_f7_S150 0.7467±0.0653             0.7500±0.0522             0.7533±0.0600
Circle_n20pct_f7_S200 0.7650±0.0561             0.7675±0.0690             0.7650±0.0561
Moons_n5pct_S100     0.9800±0.0245             0.9450±0.0522             0.9800±0.0245
Moons_n5pct_S150     0.9900±0.0213             0.9700±0.0277             0.9900±0.0213
Moons_n5pct_S200     0.9950±0.0150             0.9875±0.0168             0.9900±0.0122
Moons_n10pct_S100    0.9600±0.0436             0.9400±0.0374             0.9550±0.0350
Moons_n10pct_S150    0.9933±0.0133             0.9533±0.0306             0.9867±0.0221
Moons_n10pct_S200    0.9825±0.0160             0.9650±0.0229             0.9825±0.0160
Moons_n15pct_S100    0.9300±0.0458             0.9300±0.0458             0.9350±0.0391
Moons_n15pct_S150    0.9667±0.0394             0.9500±0.0307             0.9667±0.0394
Moons_n15pct_S200    0.9675±0.0225             0.9375±0.0202             0.9700±0.0245
Moons_n20pct_S100    0.9300±0.0510             0.9100±0.0374             0.9300±0.0458
Moons_n20pct_S150    0.9233±0.0539             0.9100±0.0473             0.9333±0.0516
Moons_n20pct_S200    0.9450±0.0332             0.9250±0.0296             0.9500±0.0354
Moons_n25pct_S100    0.9100±0.0436             0.8950±0.0472             0.9200±0.0458
Moons_n25pct_S150    0.8667±0.0730             0.8767±0.0633             0.8900±0.0651
Moons_n25pct_S200    0.9075±0.0419             0.8950±0.0384             0.9175±0.0336
Moons_n30pct_S100    0.8900±0.0539             0.8800±0.0510             0.9000±0.0387
Moons_n30pct_S150    0.8300±0.0781             0.8400±0.0742             0.8367±0.0781
Moons_n30pct_S200    0.8800±0.0367             0.8750±0.0403             0.8800±0.0367
Moons_n35pct_S100    0.8850±0.0550             0.8850±0.0550             0.8900±0.0539
Moons_n35pct_S150    0.8233±0.0775             0.8267±0.0712             0.8267±0.0786
Moons_n35pct_S200    0.8575±0.0488             0.8575±0.0501             0.8600±0.0436
Rings_3r_n5pct_S100  0.9950±0.0150             0.9200±0.0748             0.9950±0.0150
Rings_3r_n5pct_S150  0.9900±0.0300             0.9433±0.0496             0.9967±0.0100
Rings_3r_n5pct_S200  1.0000±0.0000             0.9675±0.0297             1.0000±0.0000
Rings_3r_n10pct_S100 0.9800±0.0245             0.9100±0.0663             0.9900±0.0200
Rings_3r_n10pct_S150 0.9800±0.0340             0.9267±0.0593             0.9967±0.0100
Rings_3r_n10pct_S200 0.9975±0.0075             0.9750±0.0274             0.9925±0.0115
Rings_3r_n20pct_S100 0.9300±0.0557             0.8450±0.0789             0.9600±0.0300
Rings_3r_n20pct_S150 0.9533±0.0452             0.8900±0.0578             0.9433±0.0539
Rings_3r_n20pct_S200 0.9675±0.0251             0.9400±0.0320             0.9725±0.0236
Rings_4r_n5pct_S100  0.7350±0.0867             0.6950±0.0879             0.7000±0.0806
Rings_4r_n5pct_S150  0.7367±0.0526             0.7133±0.0897             0.7167±0.0734
Rings_4r_n5pct_S200  0.7300±0.0723             0.6975±0.0564             0.7025±0.0467
Rings_4r_n10pct_S100 0.7200±0.1030             0.6800±0.0980             0.7000±0.0866
Rings_4r_n10pct_S150 0.6967±0.0795             0.6867±0.1002             0.7067±0.0940
Rings_4r_n10pct_S200 0.7050±0.0660             0.6700±0.0522             0.6975±0.0564
Rings_4r_n15pct_S100 0.7250±0.0955             0.7100±0.1091             0.7000±0.0975
Rings_4r_n15pct_S150 0.6700±0.0823             0.6667±0.0978             0.6867±0.0957
Rings_4r_n15pct_S200 0.6975±0.0637             0.6725±0.0627             0.6800±0.0660
Rings_5r_n10pct_S100 0.5850±0.0867             0.5950±0.0850             0.5900±0.0917
Rings_5r_n10pct_S150 0.6700±0.0547             0.6167±0.0860             0.6100±0.0932
Rings_5r_n10pct_S200 0.6725±0.0711             0.6650±0.0644             0.6550±0.0765
Rings_5r_n15pct_S100 0.5900±0.0583             0.5700±0.1005             0.5600±0.0970
Rings_5r_n15pct_S150 0.6567±0.0633             0.6133±0.0400             0.6133±0.0846
Rings_5r_n15pct_S200 0.6725±0.0564             0.6550±0.0678             0.6400±0.0539
XOR_S100             0.9450±0.0415             0.9450±0.0350             0.9450±0.0350
XOR_S150             0.9367±0.0526             0.9400±0.0467             0.9433±0.0616
XOR_S200             0.9650±0.0122             0.9650±0.0200             0.9625±0.0125
XOR_n5pct_S100       0.9400±0.0436             0.9450±0.0350             0.9400±0.0300
XOR_n5pct_S150       0.9467±0.0427             0.9400±0.0389             0.9367±0.0526
XOR_n5pct_S200       0.9675±0.0160             0.9650±0.0229             0.9700±0.0245
XOR_n10pct_S100      0.9400±0.0436             0.9400±0.0300             0.9400±0.0624
XOR_n10pct_S150      0.9433±0.0517             0.9367±0.0640             0.9333±0.0632
XOR_n10pct_S200      0.9650±0.0200             0.9650±0.0357             0.9625±0.0340
XOR_n15pct_S100      0.9200±0.0714             0.9250±0.0680             0.9350±0.0673
XOR_n15pct_S150      0.9300±0.0623             0.9367±0.0640             0.9333±0.0699
XOR_n15pct_S200      0.9650±0.0339             0.9575±0.0336             0.9600±0.0300
XOR_n20pct_S100      0.9350±0.0502             0.9200±0.0640             0.9200±0.0640
XOR_n20pct_S150      0.9267±0.0593             0.9300±0.0547             0.9300±0.0526
XOR_n20pct_S200      0.9700±0.0292             0.9650±0.0339             0.9650±0.0278
XOR_n25pct_S100      0.9250±0.0512             0.9000±0.0632             0.9100±0.0490
XOR_n25pct_S150      0.9200±0.0562             0.9233±0.0396             0.9200±0.0427
XOR_n25pct_S200      0.9700±0.0292             0.9600±0.0421             0.9575±0.0404
Spiral_S100          0.5900±0.1411             0.5900±0.1319             0.6200±0.1269
Spiral_S150          0.6667±0.0422             0.6600±0.0442             0.6833±0.0401
Spiral_S200          0.6475±0.0518             0.6450±0.0534             0.6600±0.0357
Spiral_n5pct_S100    0.6400±0.1562             0.6200±0.1400             0.6500±0.1245
Spiral_n5pct_S150    0.6200±0.0581             0.6167±0.0500             0.6533±0.0476
Spiral_n5pct_S200    0.6850±0.0391             0.6500±0.0371             0.6750±0.0418
Spiral_n10pct_S100   0.6750±0.1647             0.6600±0.1428             0.6750±0.1250
Spiral_n10pct_S150   0.6267±0.0696             0.5933±0.0696             0.6567±0.0633
Spiral_n10pct_S200   0.6775±0.0666             0.6800±0.0350             0.6800±0.0400
Spiral_n15pct_S100   0.6800±0.1435             0.6800±0.1229             0.6900±0.1241
Spiral_n15pct_S150   0.5900±0.0667             0.5533±0.0702             0.5967±0.0623
Spiral_n15pct_S200   0.6350±0.0539             0.6250±0.0487             0.6400±0.0682
Spiral_n20pct_S100   0.6500±0.1140             0.6600±0.1241             0.6800±0.1249
Spiral_n20pct_S150   0.5700±0.0994             0.5400±0.1062             0.5467±0.0792
Spiral_n20pct_S200   0.6350±0.0604             0.6150±0.0561             0.5925±0.0633
Spiral_n25pct_S100   0.6450±0.1193             0.6450±0.1474             0.6650±0.1415
Spiral_n25pct_S150   0.5833±0.0792             0.5733±0.0854             0.5800±0.0933
Spiral_n25pct_S200   0.6225±0.0575             0.5925±0.0922             0.5875±0.0625
Checkerboard_2x2_S100 0.9450±0.0472             0.9400±0.0436             0.9300±0.0458
Checkerboard_2x2_S150 0.9267±0.0327             0.9200±0.0400             0.9267±0.0389
Checkerboard_2x2_S200 0.9550±0.0245             0.9500±0.0250             0.9450±0.0245
Checkerboard_2x2_n5pct_S100 0.9150±0.0320             0.9100±0.0436             0.9250±0.0642
Checkerboard_2x2_n5pct_S150 0.8967±0.0547             0.8967±0.0314             0.9033±0.0458
Checkerboard_2x2_n5pct_S200 0.9450±0.0332             0.9450±0.0312             0.9475±0.0305
Checkerboard_2x2_n10pct_S100 0.8800±0.0458             0.8900±0.0583             0.8900±0.0943
Checkerboard_2x2_n10pct_S150 0.8800±0.0499             0.8733±0.0327             0.8767±0.0367
Checkerboard_2x2_n10pct_S200 0.9350±0.0278             0.9225±0.0325             0.9225±0.0361
Checkerboard_3x3_S100 0.8800±0.0640             0.8750±0.0783             0.9000±0.0837
Checkerboard_3x3_S150 0.8933±0.0533             0.8967±0.0640             0.9233±0.0616
Checkerboard_3x3_S200 0.9275±0.0344             0.9225±0.0439             0.9400±0.0255
Checkerboard_3x3_n5pct_S100 0.8550±0.0850             0.8700±0.0640             0.8600±0.0800
Checkerboard_3x3_n5pct_S150 0.8800±0.0718             0.8833±0.0885             0.8900±0.0761
Checkerboard_3x3_n5pct_S200 0.8900±0.0572             0.8650±0.0594             0.9025±0.0394
Checkerboard_3x3_n10pct_S100 0.8500±0.0775             0.8450±0.0723             0.8450±0.0757
Checkerboard_3x3_n10pct_S150 0.8267±0.0917             0.8300±0.0795             0.8533±0.0581
Checkerboard_3x3_n10pct_S200 0.7950±0.0620             0.8025±0.0518             0.8200±0.0589
Checkerboard_4x4_S100 0.7000±0.0632             0.6850±0.0923             0.7200±0.1030
Checkerboard_4x4_S150 0.6667±0.0760             0.6800±0.0686             0.7767±0.0746
Checkerboard_4x4_S200 0.7150±0.0867             0.7275±0.1104             0.8250±0.0837
Checkerboard_4x4_n5pct_S100 0.6550±0.1150             0.6200±0.1308             0.6800±0.1122
Checkerboard_4x4_n5pct_S150 0.6667±0.0683             0.6600±0.0712             0.7367±0.0706
Checkerboard_4x4_n5pct_S200 0.7575±0.0922             0.7600±0.1079             0.8600±0.0823
Checkerboard_5x5_S100 0.6500±0.0975             0.6600±0.0995             0.7250±0.0783
Checkerboard_5x5_S150 0.6833±0.0734             0.6600±0.0359             0.7200±0.0542
Checkerboard_5x5_S200 0.6525±0.0506             0.6400±0.0594             0.6900±0.1007
Iris                 1.0000±0.0000             1.0000±0.0000             1.0000±0.0000
Wine                 0.9808±0.0258             0.9808±0.0258             0.9808±0.0258
BreastCancer         0.9447±0.0167             0.9404±0.0231             0.9465±0.0177
Pima                 0.7461±0.0249             0.7455±0.0225             0.7396±0.0278
Banknote             1.0000±0.0000             0.9964±0.0033             0.9960±0.0034
Haberman             0.7500±0.0108             0.7452±0.0188             0.7419±0.0191
BreastCancer_S80     0.9563±0.0400             0.9375±0.0395             0.9375±0.0395
BreastCancer_S100    0.9600±0.0300             0.9500±0.0500             0.9500±0.0387
BreastCancer_S120    0.9500±0.0520             0.9542±0.0435             0.9458±0.0419
BreastCancer_S150    0.9733±0.0249             0.9700±0.0314             0.9800±0.0267
Pima_S80             0.6937±0.0653             0.7188±0.0640             0.7188±0.1127
Pima_S100            0.7450±0.0850             0.7550±0.0687             0.7000±0.0975
Pima_S120            0.8125±0.0678             0.8167±0.0624             0.8083±0.0750
Pima_S150            0.7667±0.0615             0.7800±0.0670             0.7533±0.0653
Banknote_S80         0.9875±0.0250             0.9563±0.0488             0.9875±0.0250
Banknote_S100        0.9700±0.0400             0.9550±0.0472             0.9700±0.0458
Banknote_S120        0.9917±0.0167             0.9667±0.0312             0.9917±0.0167
Banknote_S150        0.9733±0.0249             0.9433±0.0335             0.9733±0.0327
Haberman_S80         0.8250±0.0875             0.8250±0.0781             0.8438±0.0803
Haberman_S100        0.7950±0.0610             0.8050±0.0472             0.7950±0.0568
Haberman_S120        0.8250±0.0520             0.8208±0.0375             0.8292±0.0573
Haberman_S150        0.8167±0.0373             0.8033±0.0433             0.8100±0.0423
Wine_S80             0.9812±0.0286             0.9750±0.0306             0.9812±0.0286
Wine_S100            0.9550±0.0610             0.9600±0.0624             0.9600±0.0374
Wine_S120            0.9792±0.0280             0.9667±0.0312             0.9708±0.0325
Iris_S80             1.0000±0.0000             1.0000±0.0000             1.0000±0.0000

## 6. Ground Truth Label Generation

Generate labels for both task formulations from the evaluation results:

- **Task-A** (single-best): each dataset maps to the single encoding circuit achieving the highest accuracy, paired with the best classifier.
- **Task-B** (tolerance-based): each dataset maps to all encoding circuits within a 1% tolerance of the best accuracy, restricted to the best classifier only (no cross-classifier ties).

Restricting Task-B ties to the best classifier avoids inflating the label set with spurious matches from weaker classifiers.

In [ ]:
def label_dataframe_best_model_per_dataset(all_dataset_results, threshold=0.01):

    encodings = list(ENCODING_REGISTER.keys())
    models = ["SVM", "GPC", "KRC"]
    
    table_data = []
    tied_data = []
    
    for dataset_name, result_dict in all_dataset_results.items():
        results = result_dict["results"]
        
        best_acc = 0
        best_kernel = None
        best_model = None
        
        for enc_name in encodings:
            if enc_name in results:
                for r in results[enc_name]:
                    if r.test_accuracy > best_acc:
                        best_acc = r.test_accuracy
                        best_kernel = enc_name
                        best_model = r.model_name
        
        if best_acc == 0:
            continue
        
        table_data.append({
            "Dataset": dataset_name,
            "Best_Model": best_model,
            "Best_Kernel": best_kernel,
            "Accuracy": best_acc
        })
        
        if threshold is not None:
            for enc_name in encodings:
                if enc_name in results:
                    for r in results[enc_name]:
                        if r.model_name == best_model and r.test_accuracy >= best_acc - threshold:
                            tied_data.append({
                                "Dataset": dataset_name,
                                "Best_Model": best_model,  
                                "Best_Kernel": enc_name,
                                "Accuracy": r.test_accuracy
                            })
    
    df_best = pd.DataFrame(table_data).set_index("Dataset")
    
    if threshold is not None and tied_data:
        df_tied = pd.DataFrame(tied_data).set_index("Dataset")
        
        print("Model Distribution:")
        print("  Task-A (Best only):")
        model_counts = df_best["Best_Model"].value_counts()
        for model, count in model_counts.items():
            print(f"    {model}: {count} datasets ({count/len(df_best)*100:.1f}%)")
        
        print("\n  Task-B (Tied within best model):")
        model_counts_tied = df_tied["Best_Model"].value_counts()
        for model, count in model_counts_tied.items():
            print(f"    {model}: {count} samples ({count/len(df_tied)*100:.1f}%)")
        
        tied_per_dataset = df_tied.groupby(level=0).size()
        print(f"\n  Average tied kernels per dataset: {tied_per_dataset.mean():.2f}")
        print(f"  Min: {tied_per_dataset.min()}, Max: {tied_per_dataset.max()}")
        print()
        
        return df_best, df_tied
    
    return df_best

df_best, df_tied = label_dataframe_best_model_per_dataset(all_results, threshold=0.01)

print("="*70)
print("Task-A: Single BEST (Model + Kernel) per Dataset")
print("="*70)
print(df_best.head(10))
print(f"\nTotal samples: {len(df_best)}")

print("\n" + "="*70)
print("Task-B: Tied Kernels (within best model only)")
print("="*70)
print(df_tied.head(15))
print(f"\nTotal samples: {len(df_tied)}")

Model Distribution:
  Task 1-A (Best only):
    SVM: 113 datasets (56.5%)
    KRC: 62 datasets (31.0%)
    GPC: 25 datasets (12.5%)

  Task 1-B (Tied within best model):
    SVM: 324 samples (73.3%)
    KRC: 82 samples (18.6%)
    GPC: 36 samples (8.1%)

  Average tied kernels per dataset: 2.21
  Min: 1, Max: 6

======================================================================
Task-A: Single BEST (Model + Kernel) per Dataset
======================================================================
                Best_Model Best_Kernel  Accuracy
Dataset
Blobs_F2C2_S100        SVM      HZY_CZ       1.0
Blobs_F2C2_S150        SVM      HZY_CZ       1.0
Blobs_F2C2_S200        SVM      HZY_CZ       1.0
Blobs_F2C3_S100        SVM     HighDim       1.0
Blobs_F2C3_S150        SVM     HighDim       1.0
Blobs_F2C3_S200        SVM     HighDim       1.0
Blobs_F2C4_S100        SVM     HighDim       1.0
Blobs_F2C4_S150        SVM      HZY_CZ       1.0
Blobs_F2C4_S200        SVM     HighDim       1.0
Blobs_F3C2_S100        SVM      HZY_CZ       1.0

Total samples: 200

======================================================================
Task-B: Tied Kernels (within best model only)
======================================================================
                Best_Model          Best_Kernel  Accuracy
Dataset
Blobs_F2C2_S100        SVM              HighDim  0.995000
Blobs_F2C2_S100        SVM               HZY_CZ  1.000000
Blobs_F2C2_S100        SVM          SeparableRX  0.995000
Blobs_F2C2_S100        SVM  HardwareEfficientRx  1.000000
Blobs_F2C2_S100        SVM          ZFeatureMap  0.990000
Blobs_F2C2_S150        SVM              HighDim  0.993333
Blobs_F2C2_S150        SVM               HZY_CZ  1.000000
Blobs_F2C2_S150        SVM          SeparableRX  1.000000
Blobs_F2C2_S150        SVM  HardwareEfficientRx  0.993333
Blobs_F2C2_S200        SVM               HZY_CZ  1.000000
Blobs_F2C2_S200        SVM          SeparableRX  1.000000
Blobs_F2C2_S200        SVM  HardwareEfficientRx  1.000000
Blobs_F2C2_S200        SVM          ZFeatureMap  0.997500
Blobs_F2C3_S100        SVM              HighDim  1.000000
Blobs_F2C3_S100        SVM               HZY_CZ  1.000000

Total samples: 442

## 7. Complexity Metric Computation

Compute 24 classical complexity metrics per dataset:
- 22 metrics from Problexity (feature overlap, linearity, neighborhood, network, dimensionality, class imbalance)
- 2 metrics from Qsun in Qdata.py: Kolmogorov complexity `C(D)` and intrinsic dimensionality `dim_eff`

Metrics are computed on the training portion (scaled to [0, 1]) and averaged over 10 runs to reduce variance from stochastic metric estimators.

In [ ]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

In [ ]:
complexities_datasets = {}

for name, (X, y) in raw_datasets.items():
    complexities_train = []
    
    for i in range(10):
        seed = 42 + i
    
        X_tr, X_te, y_tr, y_te = train_test_split(
            X, y,
            test_size=0.2,
            random_state=seed,
            stratify=y
        )
        
        scaler = MinMaxScaler(feature_range=(0, 1))
        X_tr = scaler.fit_transform(X_tr)
        
        cc = px.ComplexityCalculator()
        cc.fit(X_tr, y_tr)
        results = list(cc.complexity)
        results.append(kolmogorov_complex(X_tr)['best_bytes'])
        results.append(intrinsic_dim_from_cov(X_tr))
        
        complexities_train.append(results)
    
    complexities_train = np.array(complexities_train)
    complexities_datasets[name] = np.mean(complexities_train, axis=0)

In [ ]:
labels = cc._metrics() + ['kolmogorov', 'intrinsic']
print(f"Number of metrics: {len(labels)}")
print(f"Labels: {labels}")

df = pd.DataFrame.from_dict(complexities_datasets, orient='index', columns=labels)
df

Number of metrics: 24
Labels: ['f1', 'f1v', 'f2', 'f3', 'f4', 'l1', 'l2', 'l3', 'n1', 'n2', 'n3', 'n4', 't1', 'lsc', 'density', 'clsCoef', 'hubs', 't2', 't3', 't4', 'c1', 'c2', 'kolmogorov', 'intrinsic']

,f1,f1v,f2,f3,f4,l1,l2,l3,n1,n2,...,density,clsCoef,hubs,t2,t3,t4,c1,c2,kolmogorov,intrinsic
Blobs_F2C2_S100,0.007097,0.002049,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.006250,0.016410,...,0.508924,0.004854,0.501895,0.025000,0.012500,0.500000,0.000000,0.000000,0.973534,1.017423
Blobs_F2C2_S150,0.008591,0.002415,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.004167,0.014842,...,0.511246,0.011182,0.501551,0.016667,0.008333,0.500000,0.000000,0.000000,0.961642,1.017957
Blobs_F2C2_S200,0.008600,0.002343,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.003125,0.012792,...,0.509395,0.010250,0.500931,0.012500,0.006250,0.500000,0.000000,0.000000,0.956189,1.017602
Blobs_F2C3_S100,0.004046,0.001370,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.009376,0.016809,...,0.510933,0.002781,0.490811,0.037503,0.018751,0.500000,0.000171,0.000474,0.971605,1.690905
Blobs_F2C3_S150,0.004323,0.001300,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.006250,0.013097,...,0.510992,0.007291,0.493324,0.025000,0.012500,0.500000,0.000000,0.000000,0.962416,1.685753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Haberman_S150,0.778610,0.526454,0.478999,0.881667,0.873333,0.049134,0.231667,0.2475,0.147083,0.343089,...,0.882101,0.443768,0.663996,0.025000,0.025000,1.000000,0.163359,0.357664,0.267311,2.277940
Wine_S80,0.132954,0.029516,0.000005,0.098437,0.000000,0.000060,0.001563,0.0000,0.023438,0.342321,...,0.913542,0.563211,0.766817,0.203125,0.146875,0.723077,0.006349,0.017425,0.590979,4.218631
Wine_S100,0.169042,0.033700,0.000017,0.217500,0.000000,0.000030,0.003750,0.0000,0.028750,0.341432,...,0.935854,0.634435,0.800864,0.162500,0.125000,0.769231,0.007226,0.019802,0.570901,4.462597
Wine_S120,0.174444,0.035494,0.000024,0.211458,0.000000,0.000096,0.004167,0.0000,0.030729,0.347073,...,0.924518,0.595590,0.788415,0.135417,0.104167,0.769231,0.007841,0.021468,0.544426,4.768309
Iris_S80,0.027863,0.008986,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.007812,0.102990,...,0.745833,0.217790,0.625850,0.062500,0.031250,0.500000,0.000000,0.000000,0.295930,1.312214

### 7.1 Merge Labels with Metrics

Join the Task-A best encoding circuit label with the complexity metric matrix to form the synthesis DataFrame — one row per dataset, 24 metric columns plus one label column.

In [ ]:
df["Best_Kernel"] = df_best["Best_Kernel"]
df

,f1,f1v,f2,f3,f4,l1,l2,l3,n1,n2,...,clsCoef,hubs,t2,t3,t4,c1,c2,kolmogorov,intrinsic,Best_Kernel
Blobs_F2C2_S100,0.007097,0.002049,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.006250,0.016410,...,0.004854,0.501895,0.025000,0.012500,0.500000,0.000000,0.000000,0.973534,1.017423,HZY_CZ
Blobs_F2C2_S150,0.008591,0.002415,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.004167,0.014842,...,0.011182,0.501551,0.016667,0.008333,0.500000,0.000000,0.000000,0.961642,1.017957,HZY_CZ
Blobs_F2C2_S200,0.008600,0.002343,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.003125,0.012792,...,0.010250,0.500931,0.012500,0.006250,0.500000,0.000000,0.000000,0.956189,1.017602,HZY_CZ
Blobs_F2C3_S100,0.004046,0.001370,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.009376,0.016809,...,0.002781,0.490811,0.037503,0.018751,0.500000,0.000171,0.000474,0.971605,1.690905,HighDim
Blobs_F2C3_S150,0.004323,0.001300,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.006250,0.013097,...,0.007291,0.493324,0.025000,0.012500,0.500000,0.000000,0.000000,0.962416,1.685753,HighDim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Haberman_S150,0.778610,0.526454,0.478999,0.881667,0.873333,0.049134,0.231667,0.2475,0.147083,0.343089,...,0.443768,0.663996,0.025000,0.025000,1.000000,0.163359,0.357664,0.267311,2.277940,ZFeatureMap
Wine_S80,0.132954,0.029516,0.000005,0.098437,0.000000,0.000060,0.001563,0.0000,0.023438,0.342321,...,0.563211,0.766817,0.203125,0.146875,0.723077,0.006349,0.017425,0.590979,4.218631,HardwareEfficientRx
Wine_S100,0.169042,0.033700,0.000017,0.217500,0.000000,0.000030,0.003750,0.0000,0.028750,0.341432,...,0.634435,0.800864,0.162500,0.125000,0.769231,0.007226,0.019802,0.570901,4.462597,HighDim
Wine_S120,0.174444,0.035494,0.000024,0.211458,0.000000,0.000096,0.004167,0.0000,0.030729,0.347073,...,0.595590,0.788415,0.135417,0.104167,0.769231,0.007841,0.021468,0.544426,4.768309,HardwareEfficientRx
Iris_S80,0.027863,0.008986,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.007812,0.102990,...,0.217790,0.625850,0.062500,0.031250,0.500000,0.000000,0.000000,0.295930,1.312214,HighDim

## 8. Save Outputs

Save three CSV files consumed by the downstream Majority Voting and LOOCV notebooks:
- `taska_labels.csv` — single-best labels
- `taskb_labels.csv` — expanded tolerance-based labels
- `synthesis_df.csv` — complexity metrics + Task-A labels (meta-dataset)

In [ ]:
df_best.to_csv("results/taska_labels.csv", index=True)
print("Saved: results/taska_labels.csv")

df_tied.to_csv("results/taskb_labels.csv", index=True)
print("Saved: results/taskb_labels.csv")

df.to_csv("results/synthesis_df.csv", index=True)
print("Saved: results/synthesis_df.csv")

Saved: results/taska_labels.csv
Saved: results/taskb_labels.csv
Saved: results/synthesis_df.csv